/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/q78qlbK
 */
import {
  AccordionTrigger,
  AccordionContent,
  AccordionItem,
  Accordion,
} from "@/components/landing/ui/accordion"

export function FAQ() {
  return (
    <Accordion className="w-full mt-4" type="multiple">
      <AccordionItem value="item-0">
        <AccordionTrigger className="hover:underline-none">
          What is Chattiphy?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Chattiphy is a WhatsApp-first AI chatbot workspace for support teams, sales
          teams, and operators who want faster replies, lead capture, and flexible bot
          control from one dashboard.
        </AccordionContent>
      </AccordionItem>

      <AccordionItem value="item-1">
        <AccordionTrigger className="hover:underline-none">
          How does pricing work?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          The app is free to use. You bring your own model or provider key, so your usage
          cost stays under your control and gets billed directly by your provider.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-2">
        <AccordionTrigger className="hover:underline-none">
          Can I use it for support and lead capture at the same time?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Yes. You can answer common customer questions, qualify inbound interest, and
          collect contact details or handoff requests in the same workflow.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-3">
        <AccordionTrigger className="hover:underline-none">
          Can I connect my own knowledge base?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Yes. You can use website content, uploaded documents, and your own prompt or
          business instructions so the bot answers based on your real operations.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-4">
        <AccordionTrigger className="hover:underline-none text-left">
          Is the live demo already available?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Not yet. We have kept the demo section on the landing page as a preview area,
          but the interactive widget will be connected after the next migration step.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem className="border-b-0" value="item-5">
        <AccordionTrigger className="hover:underline-none text-left">
          Can a human take over conversations when needed?
        </AccordionTrigger>
        <AccordionContent className="text-muted-foreground">
          Yes. The goal is not to replace your team, but to remove repetitive work and
          route higher-value conversations to a human when context or judgment matters.
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  )
}
